### ISSUE TITLE
Development notes for TinyLogicFriend

### ISSUE THREAD

**Issue by kmatch98** [kmatch98/tinylogicfriend#1]
This is where I will capture my thought processes as I go through the process of developing further from tannewt's orginial repository of TinyLogicFriend logic analyzer using low-cost microcontrollers.

Main objective
--------------
1. Utilize low-cost microcontroller boards to use as logic analyzers when connected with a host computer
2. Provide easy-to-load UF2 files for boards to make them act as a logic analyzer (later can be expanded to other functions)
3. `sigrok` will autodetect the pin names and capabilities (sampling rate) of a board, setup pins, triggers and other options, start runs and collect data from the board

Related projects
-----------------
I discovered two projects with similar objectives:
- [Pico-Logic](https://github.com/markb139/pico_logic) by @markb139 uses a Raspberry Pi Pico and PIO with DMA (direct memory access) as a logic analyzer. Objective is to talk to sigrok over USBTMC using SCPI commands.
- [SAMD21-USBTMC](https://github.com/charkster/samd21-usbtmc) by @charkster uses a SAMD21 to write analog and digital output values from inputs received from a host over USBTMC and communicates using SCPI commands. Mentions an issue with using the DAC and USB at the same time on SAMD21

Main software components
---------------------------
- TinyLogicFriend - This is the software the runs on microcontrollers that reads pin values and sends the value and timing to a Host computer using USB.  This was initiated by @tannewt in the github repo [/tannewt/tinylogicfriend](https://github.com/tannewt/tinylogicfriend).  Here is a [great video by tannewt that describes the objectives](https://www.youtube.com/watch?v=qetJHmfNA_g).
- [sigrok](https://sigrok.org) - This is the overall project name of software programs that run on the Host computer that communicate with logic analyzers and other test equipment and capture, decode and analyze the signals. 
    - [sigrok-cli](https://github.com/sigrokproject/sigrok-cli) - The command-line interface to the sigrok tools.
    - [PulseView](https://github.com/sigrokproject/pulseview) - The visual software that allows for easy connection to devices and visual decoding and analysis of waveforms.  This is really cool.
    - [libsigrok -](https://github.com/sigrokproject/libsigrok) This is the code that defines the host-side interface to devices.  Each device type has an entry in the code (see `libsigrok/src/hardware`, or run `sigrok-cli -L` to list the devices that are supported).

Project structure
-----------------
- TinyLogicFriend code runs on the microcontroller and measures the pins.  It sends run-length-encoded (RLE) measurments to the host computer via USB.
- sigrok code runs on the host computer.  sigrok communicates with the TinyLogicFriend USB device to:
   - Read the TinyLogicFriend capabilities: pin names, sample rates
   - Set the pins to be measured
   - Setup the sampling rate
   - Setup the number of samples to be measured
   - Setup the triggers
   - Start (Run)
   - Stop

Making the connection
-----------------------
The sigrok code communicates to TinyLogicFriend over USB.  In order to maximize the possible sampling rate, we want a high throughput over the USB bus. Two options may be suitable for USB connections for fast communications, either Bulk transfer or Isochronous communication.  
**Due to the complexity of the Isochronous communication, I think it's best to start with the Bulk transfer method.**

There are various pre-defined [USB Classes](https://www.usb.org/defined-class-codes) that can be used.  I think it is best to use an existing class rather than define a custom one.  Right now I am considering the following USB structure.  (Currently, I'm learning the differences between classes and interfaces, so it's a big blurry for me.  I hope to clarify the differences so I can use these.)

- [CDC Communications Device Class](https://www.usb.org/defined-class-codes#anchor_BaseClass02h) - This is good for bulk transfer and is well known.  But, it's not really designed for test equipment communications.
- [TMC - Test and Measurement Class](https://www.usb.org/document-library/test-measurement-class-specification) - See "Base Class FEh" - This was developed for the purposes of communicating from a host computer to test equipment.  Since a logic analyzer is test equipment, this probably is the right approach.  I think this was originally developed as an equivalent to the widely-used GPIB (and SCPI command) interface for test equipment.

Possible limitations
-------------------
- The interrupts can be programmed to use input filtering.  Due to the additional clock cycles required for filtering, this will add latency that may be the limiting factor for the sampling rate (needs further analysis).

USB Resources
----------------
[Beyond Logic](https://www.beyondlogic.org/usbnutshell/usb1.shtml) - This gives a good background on USB, including classes, interface and endpoints.
[Microchip Developer Lessons](https://microchipdeveloper.com/usb:start) -  Another good background on USB, including a [good chart that highlight the throughput of the different transfer types (Bulk, Isochronous, etc.)](https://microchipdeveloper.com/usb:frames)

Microcontroller USB
--------------------
[TinyUSB](https://github.com/hathach/tinyusb) is what I plan to use.  It has both CDC and TMC examples, so it's a great starting point.  Also, it supports a lot of the chips that are used on Adafruit boards.
- Here's an [introduction to using TinyUSB](https://www.pschatzmann.ch/home/2021/02/19/tinyusb-a-simple-tutorial/)
- To do: I need to understand how the TMC example handles the instrument commands.  

sigrok USB
-----------
The libsigrok code already uses [libusb](http://libusb.sourceforge.net/api-1.0/), so that's what I'll use.  [There is existing support for SCPI and USBTMC in sigrok.](https://github.com/sigrokproject/libsigrok/blob/master/src/scpi/scpi_usbtmc_libusb.c)
   
Command set: SCPI
--------------------
To make it similar to other test equipment, it may be desirable to utilize some SCPI commands where possible.
SCPI commands are 4-character commands used to communicate with instruments. [Specs are here](https://www.ivifoundation.org/docs/scpi-99.pdf).

**Comment by kmatch98** [comment]
Project update: I now have `sigrok` and my TinyLogicFriend talking. I tweaked the tinyUSB example code that was used by @charkster and added that the device would recognize a command “LUVU” in the `tud_usbtmc_msg_data_cb` “Message data callback” function. 

Then I added a state variable to signal it to respond with “LUVU2” in the `usbtmc_app_task_iter` USB-TMC “task iteration function” that is run in the continuous loop of the `main` function.  

I hacked the `libsigrok` USBTMC code to send the “LUVU” to the TinyLogicFriend, along with a few logging statements to capture the event. Here’s the log output!  My first call and response!

![TinyLogicFriend%20-%20LUV](https://user-images.githubusercontent.com/33587466/113489596-bc457b80-948a-11eb-9fbc-9027213c96e8.jpeg)

**Comment by charkster** [comment]
Wow, looks like a very cool project! I'm using a $10 8 channel 24MHz usb 2.0 logic analyzer from Amazon, and it runs sigrok's pulseview very well. Are you going to make a similar one? One product that is not inexpensively available yet is a USB 3.0 logic analyzer. This would be a clone of the Saleae Logic Pro 8.
Also, there are some SCPI parsing C libraries on GitHub that could be useful if you want to implement lots of commands. Using them is beyond my programming ability... I just stayed simple.

**Comment by kmatch98** [comment]
> Also, there are some SCPI parsing C libraries on GitHub that could be useful if you want to implement lots of commands. 

Thanks that’s a great tip. Looks like there is a good SCPI parser that may make it (relatively) straightforward to tweak with different capability. This one looks pretty well developed. 

https://github.com/j123b567/scpi-parser

This library has several examples, so this is a great starting point. Thanks again for your note, it is a great suggestion.

**Comment by charkster** [comment]
That's the same project I was looking at using. I was not sure how much memory it would use or how steep the learning curve would be. It looks very impressive.

**Comment by kmatch98** [comment]
Other SCPI parsers to consider:
- https://github.com/MightyPork/scpi_parser
- https://github.com/LachlanGunn/oic Open Instrument Controller
- https://github.com/charlesbaynham/MicroprocessorSCPI SCOPI Decoder, no dynamic memory allocations used, in C++

**Comment by markb139** [comment]
As an update to my project. I've pushed up my libsigrok fork. After chasing a bug I introduced, I've now got the code working at upto max clock speed (125MHz), though there is only 200K of RAM :(

I need to be able to configure the trigger edges. 
I also want to implement some code to improve memory usage if you are sampling less than 8 bits. Sigrok can only (it seems to me) handle bytes as the smallest unit of capture. So, if you are capturing 1 bit then you are wasting space, which is not ideal when you only have 200K. My idea is to capture the data on the pico in an efficient manner, then expand as necessary in the sigrok code.

All in all, for £4 it's a great logic analyzer :)

**Comment by kmatch98** [comment]
@markb139 Great progress, I'm watching your project closely to learn from you.

Just to put some numbers to it, I added the [scpi-parser](https://github.com/j123b567/scpi-parser) to my basic project and the code increased from 8kB up to 37kB, net increase of 30kB ([Adafruit ItsyBitsyM4](https://learn.adafruit.com/introducing-adafruit-itsybitsy-m4?view=all).  

I am still figuring out how to integrate the scpi-parser library into the code.  I now have initial contact between sigrok and my ItsyBitsy M4 running with the parser.  This is the first time I'm compiling a C project from several different libraries so I've been working my way up the learning curve for Makefiles and how to tell it where files are located.  Now I'm thinking about how my project file structure is organized to combine [tinyUSB](https://github.com/hathach/tinyusb) and [scpi-parser](https://github.com/j123b567/scpi-parser).

### Decisions on using scpi-parser:
I think that most "fast" boards will probably come with a decent enough RAM (like [Teensy 4.1](https://www.pjrc.com/store/teensy41.html)).  The smaller boards (like Cortex M4 or even Cortex M0 boards) will probably not have enough RAM to store many measurements, so they will probably need to stream directly to USB at a modest sampling rate.  For these reasons, I'm currently leaning toward using the scpi-parser library, since it's fairly clear how to add commands.  But I'll spend some more time on it and see how it goes.  

### Initial board selections:
- [Adafruit ItsyBitsyM4](https://learn.adafruit.com/introducing-adafruit-itsybitsy-m4?view=all) - the original [TinyLogicFriend](https://github.com/tannewt/tinylogicfriend) by was using Cortex M4 and because I have one handy on my bench.  I think this will be a good starting point to explore streaming over USB at relatively low rates.  
- [Raspberry Pi Pico](https://www.raspberrypi.org/products/raspberry-pi-pico/) or other RP2040 boards - probably start with the Raspberry Pi Pico since there is available sampling code from @gamblor21 and @markb139 (using DMA). So far, these two are organized to sample quickly storing the measurements in RAM, and then they push the results over USB.
- [Teensy 4.1](https://www.pjrc.com/store/teensy41.html) - Super fast and has USB 2.0.  This is the best chance of streaming decently high-sampling rate data over USB.  On the flip side, this board also has room for additional RAM, this an option that might be exploited in "store samples" mode.

**Comment by markb139** [comment]
Hi @kmatch98,
I've had some spare time this week, so I've been working on my project.
I'm not new to C programming, but it's been a long time since I did C programming as a job. So some re-learning for me.
The Pico has 260K of RAM, which is quite a lot. I'm hoping to create some space saving optimisations so that I can capture more than 200K samples.
I've not look at any parsers for SCPI commands. At the moment, my implementation is so simple I can create my own.

I'm currently looking at adding signal generation. I have a simple square wave being generated.

**Comment by kmatch98** [comment]
Great progress @markb139.  I’m still not fully convinced about the parser but once you have on command you think about adding another!  The long “if” gets big, but maybe folks used to C are used to that (?)

Here’s the starting command set I’m thinking about for a device acting as a logic analyzer:

## Command definition

- [x] `CHANnel:COUNT?` Get number of channels

- [x] `CHANnel<n>:NAME?` Get channel number \<n\> name

- [x] `CHANnel<n>:STATus` either  `OFF` or `ON` Set channel reading status

- [x] `CHANnel<n>:STATus?` Get channel read status

- [ ] `CHANnel<n>:FILTer` either `OFF` or `ON` For Run-length encoding mode, whether filtering is placed on the interrupt pin. (Is interrupt filtering applied for all pins or each individually?)

- [ ] `CHANnel<n>:FILTer?` Get filter status, only relevant when `MODE RLE`

- [x] `TRIGger:OPTions?`

    Get trigger options `<v>`
    * X=trigger off
    * 0=on zero
    * 1=on one
    * R=rising
    * F=falling
    * E=any edge

- [x] `CHANnel<n>:TRIGger <v>` Set trigger type

- [x] `CHANnel<n>:TRIGger?` Get trigger type for channel `<n>`

- [x] `RATE:MIN?` Get *minimum* sampling rate (in Hz)

- [x] `RATE:MAX?` Get *maximum* sampling rate (in Hz)

- [x] `RATE:STEP?` Get sampling rate step size (in Hz)

- [x] `RATE <xxxx>` Set sampling rate

- [x] `RATE?` Get sampling rate

- [x] `SAMPles <xxx>` Set number of samples to be captured. Set to 0 for continuous sampling. Sample count is relative to the sampling rate clock, even when run-length encoding is used

- [x] `SAMPles?` Get number of samples

- [] `SAMPles:MAX?` Get maximum number of samples

- [ ] `MODE <Y>` Either `RLE` or `CLOCK`.  Run-length encoded or sample at configured sampling rate. 

- [ ] `MODE?` Either `RLE` or `CLOCK`

- [x] `Run`

- [ ] `STOP`

**Comment by markb139** [comment]
You are correct, my code will get messy and will need a better parser solution soon. 
The pico board has plenty of storage, so program size isn't an issue

**Comment by kmatch98** [comment]
I've got the scpi-parser integrated into the **_TinyLogicFriend_** for reading and parsing command and sending back responses.

I've got two commands integrated to **_sigrok_** for getting the number of channels `CHANnel:COUNT?` and the channel names `CHANnel#:NAME?`:

```
sr: [00:01.029968] scpi_usbtmc: Successfully sent SCPI command: 'CHANnel:COUNT?'.
sr: [00:01.286185] scpi: Got response: '16', length 2.
sr: [00:01.286247] tiny-logic-friend-la: chan_count = 16
sr: [00:01.286608] scpi_usbtmc: Successfully sent SCPI command: 'CHANnel1:NAME?'.
sr: [00:01.537778] scpi: Got response: 'D5', length 2.
sr: [00:01.537799] tiny-logic-friend-la: send: CHANnel1:NAME?, chan #: 1, channel name: D5
sr: [00:01.538017] scpi_usbtmc: Successfully sent SCPI command: 'CHANnel2:NAME?'.
sr: [00:01.790109] scpi: Got response: 'SCK', length 3.
sr: [00:01.790174] tiny-logic-friend-la: send: CHANnel2:NAME?, chan #: 2, channel name: SCK
sr: [00:01.790450] scpi_usbtmc: Successfully sent SCPI command: 'CHANnel3:NAME?'.
sr: [00:02.042139] scpi: Got response: 'D6', length 2.
sr: [00:02.042161] tiny-logic-friend-la: send: CHANnel3:NAME?, chan #: 3, channel name: D6
sr: [00:02.042403] scpi_usbtmc: Successfully sent SCPI command: 'CHANnel4:NAME?'.
sr: [00:02.294311] scpi: Got response: 'D9', length 2.
sr: [00:02.294332] tiny-logic-friend-la: send: CHANnel4:NAME?, chan #: 4, channel name: D9
sr: [00:02.294562] scpi_usbtmc: Successfully sent SCPI command: 'CHANnel5:NAME?'.
sr: [00:02.546402] scpi: Got response: 'A4', length 2.
sr: [00:02.546424] tiny-logic-friend-la: send: CHANnel5:NAME?, chan #: 5, channel name: A4
sr: [00:02.546627] scpi_usbtmc: Successfully sent SCPI command: 'CHANnel6:NAME?'.
sr: [00:02.798403] scpi: Got response: 'A1', length 2.
sr: [00:02.798437] tiny-logic-friend-la: send: CHANnel6:NAME?, chan #: 6, channel name: A1
sr: [00:02.798628] scpi_usbtmc: Successfully sent SCPI command: 'CHANnel7:NAME?'.
sr: [00:03.050611] scpi: Got response: 'A5', length 2.
sr: [00:03.050633] tiny-logic-friend-la: send: CHANnel7:NAME?, chan #: 7, channel name: A5
sr: [00:03.050930] scpi_usbtmc: Successfully sent SCPI command: 'CHANnel8:NAME?'.
sr: [00:03.302673] scpi: Got response: 'MOSI', length 4.
sr: [00:03.302696] tiny-logic-friend-la: send: CHANnel8:NAME?, chan #: 8, channel name: MOSI
sr: [00:03.303003] scpi_usbtmc: Successfully sent SCPI command: 'CHANnel9:NAME?'.
sr: [00:03.554904] scpi: Got response: 'A2', length 2.
sr: [00:03.554926] tiny-logic-friend-la: send: CHANnel9:NAME?, chan #: 9, channel name: A2
sr: [00:03.555158] scpi_usbtmc: Successfully sent SCPI command: 'CHANnel10:NAME?'.
sr: [00:03.806848] scpi: Got response: 'A3', length 2.
sr: [00:03.806870] tiny-logic-friend-la: send: CHANnel10:NAME?, chan #: 10, channel name: A3
sr: [00:03.807159] scpi_usbtmc: Successfully sent SCPI command: 'CHANnel11:NAME?'.
sr: [00:04.059046] scpi: Got response: 'n/c', length 3.
sr: [00:04.059082] tiny-logic-friend-la: send: CHANnel11:NAME?, chan #: 11, channel name: n/c
sr: [00:04.059310] scpi_usbtmc: Successfully sent SCPI command: 'CHANnel12:NAME?'.
sr: [00:04.311279] scpi: Got response: 'n/c', length 3.
sr: [00:04.311298] tiny-logic-friend-la: send: CHANnel12:NAME?, chan #: 12, channel name: n/c
sr: [00:04.311635] scpi_usbtmc: Successfully sent SCPI command: 'CHANnel13:NAME?'.
sr: [00:04.563327] scpi: Got response: 'SDA', length 3.
sr: [00:04.563348] tiny-logic-friend-la: send: CHANnel13:NAME?, chan #: 13, channel name: SDA
sr: [00:04.563570] scpi_usbtmc: Successfully sent SCPI command: 'CHANnel14:NAME?'.
sr: [00:04.815535] scpi: Got response: 'SCL', length 3.
sr: [00:04.815600] tiny-logic-friend-la: send: CHANnel14:NAME?, chan #: 14, channel name: SCL
sr: [00:04.815853] scpi_usbtmc: Successfully sent SCPI command: 'CHANnel15:NAME?'.
sr: [00:05.067646] scpi: Got response: 'D4', length 2.
sr: [00:05.067671] tiny-logic-friend-la: send: CHANnel15:NAME?, chan #: 15, channel name: D4
sr: [00:05.067923] scpi_usbtmc: Successfully sent SCPI command: 'CHANnel16:NAME?'.
sr: [00:05.319700] scpi: Got response: 'n/c', length 3.
sr: [00:05.319720] tiny-logic-friend-la: send: CHANnel16:NAME?, chan #: 16, channel name: n/c
```

**Comment by kmatch98** [comment]
My project structure is pretty disjoint right now.  I've been working inside of `tinyUSB/examples/device/usbtmc` for my TinyLogicFriend code.  For now everything is compiling ok, but eventually I will need to reorganize the tinyLogicFriend files and make tinyUSB as a submodule.

Anyway, for now my latest commits for the tinyLogicFriend code will be stored here:
https://github.com/kmatch98/tinyusb/tree/master/examples/device/usbtmc

**Comment by kmatch98** [comment]
Now I’m figuring out how to get all the settings into libsigrok. So far I have functions to get channel count, the channel names, the channel enable/disable, the range of sample rates and sample rate setting functions.

To do:
Store Trigger options
Set trigger for each channel 
Set/get number of samples 

I’m still learning about the structures that I need to fill in libsigrok. I need to finalize what settings I will support and then write the code to handle each of those settings. There are three places for handling each setting:
- `config_get`
- `config_set`
- `config_lis`

These need entries for each of the `key` values that are set in the `devopts` device options variable.  Also I should consider making `devopts` as mutable based on the input from the TinyLogicFriend board.  That will stay on the to do list.

**Comment by kmatch98** [comment]
Some more related projects

- https://github.com/thanks4opensource/buck50 ESP32
- https://github.com/LAtimes2/TeensyLogicAnalyzer Teensy 4.1

**Comment by kmatch98** [comment]
Ok, I think I have a better idea of the organization of the `api.c` file.  I now have the `--scan` and `--show` options working.  

There are some discrepancies between how sigrok expects things to work and how TinyLogicFriend is organized.
When running the `--show` command to show the capabilities of a driver, `sigrok-cli` calls all of the options to verify they are working.  However, it does not perform the `scan` function prior to doing this.  So, that means that the scpi variable isn't setup yet when it calls the `config_list` options.

For the way most of the sigrok hardware drivers are setup, all the options are defined in the sigrok driver.  So, for these existing drivers, if `config_list` wants to check all the trigger options, it can do this without even talking to the device, since all the constant are already defined by the sigrok driver code. [Wild speculation: Perhaps the design of the drivers was intentional so that a driver capability could be queried without having a device connected.]

In contrast, the TinyLogicFriend is configured so that the driver options are not defined at compile time.  In contrast, the code reaches out and talks to the TinyLogicFriend to check its options (as a good friend should). 

To accommodate this difference, I setup the `config_set`, `config_get` and `config_list` commands to check whether the `sr_device_instance` is valid or not prior to checking the configuration parameter requested.  If this functions is called with an invalid `sr_device instance`, this gives the following error message:
```
Must call `scan` prior to calling `config_list`.
```

Both the `--scan` and `--show` commands both seem to recover from this error.  

Here is a successful response to the `--show` command:

```
margaret@iMac macosx % sigrok-cli -d tiny-logic-friend-la -l 4 --show
sr: [00:00.000001] log: libsigrok loglevel set to 4.
sr: [00:00.000038] backend: libsigrok 0.6.0-git-3d5a919d/4:0:0.
sr: [00:00.000081] backend: Libs: glib 2.68.1 (rt: 2.68.1/6801:1), libzip 1.7.3, libserialport 0.1.1/1:0:1 (rt: 0.1.1/1:0:1), libusb-1.0 1.0.24.11584 API 0x01000108, libftdi 1.5.
sr: [00:00.000090] backend: Host: x86_64-apple-darwin20.3.0, little-endian.
sr: [00:00.000097] backend: SCPI backends: TCP, RPC, serial, USBTMC.
sr: [00:00.000101] backend: Firmware search paths:
sr: [00:00.000130] backend:  - /Users/margaret/.local/share/sigrok-firmware
sr: [00:00.000136] backend:  - /Users/margaret/sr_macosx/share/sigrok-firmware
sr: [00:00.000140] backend:  - /usr/local/share/sigrok-firmware
sr: [00:00.000145] backend:  - /usr/share/sigrok-firmware
srd: libsigrokdecode loglevel set to 4.
sr: [00:00.061133] tiny-logic-friend-la: Must call `scan` prior to calling `config_list`.
sr: [00:00.061143] tiny-logic-friend-la: Must call `scan` prior to calling `config_list`.
sr: [00:00.061243] scpi_usbtmc: Found USBTMC device (VID:PID = cafe:4000, bus.address = 20.28).
sr: [00:00.061280] scpi: Opening USBTMC device usbtmc/20.28.
sr: [00:00.061492] usb: Found USB device (VID:PID = cafe:4000, bus.address = 20.28).
sr: [00:00.061518] usb: Trying to open USB device 20.28.
sr: [00:00.061656] usb: Opened USB device (VID:PID = cafe:4000, bus.address = 20.28).
sr: [00:00.061669] scpi_usbtmc: Interface 0 configuration 1.
sr: [00:00.061675] scpi_usbtmc: Bulk OUT EP 1
sr: [00:00.061680] scpi_usbtmc: Bulk IN EP 1
sr: [00:00.061684] scpi_usbtmc: Interrupt EP 2
sr: [00:00.062775] scpi_usbtmc: Device capabilities: L4, T6, SR0, RL0, DT1
sr: [00:04.607892] tiny-logic-friend-la: Setting all channels on, configuring channels
sr: [00:05.629340] usb: Closed USB device 20.28.
tiny-logic-friend-la - AdafruitIndustries TinyLogicFriend ItsyBitsyM4 [S/N: 21-04] with 16 channels: D5 SCK D6 D9 A4 A1 A5 MOSI A2 A3 n/c n/c SDA SCL D4 n/c
sr: [00:05.630919] device: tiny-logic-friend-la: Opening device instance.
sr: [00:05.630929] usb: Trying to open USB device 20.28.
sr: [00:05.631037] usb: Opened USB device (VID:PID = cafe:4000, bus.address = 20.28).
sr: [00:05.631063] scpi_usbtmc: Interface 0 configuration 1.
sr: [00:05.631069] scpi_usbtmc: Bulk OUT EP 1
sr: [00:05.631074] scpi_usbtmc: Bulk IN EP 1
sr: [00:05.631079] scpi_usbtmc: Interrupt EP 2
sr: [00:05.632017] scpi_usbtmc: Device capabilities: L4, T6, SR0, RL0, DT1
Supported configuration options:
    limit_samples: 
    samplerate (1 Hz - 20 MHz in steps of 1 Hz)
    enabled: on, off
    Supported triggers: 0 1 r f e 
    logic_channels
sr: [00:05.884907] device: tiny-logic-friend-la: Closing device instance.
sr: [00:05.885126] usb: Closed USB device 20.28.
sr: [00:05.885141] hwdriver: Cleaning up all drivers.
```
